apiVersion: appstore.eda.nokia.com/v1
kind: AppInstaller
metadata:
  generateName: netbox-install-
  namespace: eda-system
spec:
  operation: install
  apps:
    - appId: netbox.eda.nokia.com
      catalog: eda-catalog-builtin-apps
      version:
        type: semver
        value: v4.0.0
