apiVersion: fabrics.eda.nokia.com/v1
kind: Fabric
metadata:
  name: netbox-ebgp-fabric
  namespace: eda-netbox
spec:
  leafs:
    leafNodeSelectors:
      - eda.nokia.com/role=leaf
  spines:
    spineNodeSelectors:
      - eda.nokia.com/role=spine
  interSwitchLinks:
    linkSelectors:
      - eda.nokia.com/role=interSwitch
    poolIPv4: nb-isl-v4
    poolIPv6: nb-isl-v6
  systemPoolIPv4: nb-systemip-v4
  systemPoolIPv6: nb-systemip-v6
  underlayProtocol:
    bgp:
      asnPool: asn-pool
    protocols:
      - EBGP
  overlayProtocol:
    protocol: EBGP
